<a href="https://colab.research.google.com/github/RivuSengupta/RivuSengupta/blob/main/Classification_Bank_Fraud_Detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
uploaded = files.upload()

Saving churn.csv to churn.csv


In [76]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
from sklearn import metrics
from sklearn.impute import SimpleImputer
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LinearRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import roc_auc_score

In [77]:
imp = pd.read_csv("churn.csv")

In [78]:
def split_data(imp, drop_list):
  churn = imp.drop(drop_list, axis=1)
  print(imp.columns)
  #test train split time
  from sklearn.model_selection import train_test_split
  y = imp['Exited'].values #target
  X = imp.drop(['Exited'], axis=1).values #features
  X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)
  print("Train set size = ", len(y_train))
  print("Test set size = ", len(y_test))
  print("Fraud Cases in Test Set = ", sum(y_test))
  print("Train set size = ", len(y_train))
  return X_train, X_test, y_train, y_test

In [79]:
def get_predictions(clf, X_train, y_train, X_test):
  #create classifier
  clf =clf
  #fit it to the training data
  clf.fit(X_train, y_train)
  #predict using test data
  y_pred = clf.predict(X_test)
  #compute predicted probilities y_pred_prob
  y_pred_prob = clf.predict_proba(X_test)
  #for fun: train set prediction
  train_pred = clf.predict(X_train)
  print("Train set confusion matrix= ", confusion_matrix(y_train, train_pred))
  return y_pred, y_pred_prob

In [80]:
def print_scores(y_test, y_pred, y_pred_prob):
  print("test set confusion_matrix:\n", confusion_matrix(y_test, y_pred))
  print("Recall Score: ", recall_score(y_test, y_pred))
  print("Precision Score: ", precision_score(y_test, y_pred))
  print("F1 Score: ", f1_score(y_test, y_pred))
  print("accuracy Score: ", accuracy_score(y_test, y_pred))
  print("ROC AUC: {} ".format(roc_auc_score(y_test, y_pred_prob[:,1])))

In [81]:
imp = pd.read_csv("churn.csv")

In [82]:
drop_list = []
X_train, X_test, y_train, y_test = split_data(imp, drop_list)

Index(['Male', 'Germany', 'Spain', 'CreditScore', 'Age', 'Tenure', 'Balance',
       'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary',
       'Exited'],
      dtype='object')
Train set size =  5106
Test set size =  1277
Fraud Cases in Test Set =  307
Train set size =  5106


In [83]:
y_pred, y_pred_prob = get_predictions(GaussianNB(), X_train, y_train, X_test)

Train set confusion matrix=  [[3707  169]
 [1145   85]]


In [84]:
print_scores(y_test, y_pred, y_pred_prob)

test set confusion_matrix:
 [[931  39]
 [270  37]]
Recall Score:  0.12052117263843648
Precision Score:  0.4868421052631579
F1 Score:  0.19321148825065274
accuracy Score:  0.7580266249021144
ROC AUC: 0.7623761711273045 


In [85]:
y_pred, y_pred_prob = get_predictions(KNeighborsClassifier(), X_train, y_train, X_test)

Train set confusion matrix=  [[3697  179]
 [ 932  298]]


In [86]:
print_scores(y_test, y_pred, y_pred_prob)

test set confusion_matrix:
 [[878  92]
 [279  28]]
Recall Score:  0.09120521172638436
Precision Score:  0.23333333333333334
F1 Score:  0.13114754098360656
accuracy Score:  0.7094753328112764
ROC AUC: 0.49897075120051043 


In [87]:
y_pred, y_pred_prob = get_predictions(LogisticRegression(), X_train, y_train, X_test)

Train set confusion matrix=  [[3735  141]
 [1153   77]]


In [88]:
print_scores(y_test, y_pred, y_pred_prob)

test set confusion_matrix:
 [[946  24]
 [279  28]]
Recall Score:  0.09120521172638436
Precision Score:  0.5384615384615384
F1 Score:  0.15598885793871864
accuracy Score:  0.7627251370399374
ROC AUC: 0.7151818395513617 
